### ISSUE TITLE
Issue with removing comments in ccg.py files

### ISSUE THREAD

**Issue by YaLing-Luo0** [oceaneLIU/GraphCoder#1]
Thank you very much for the contributions of the authors. While attempting to implement the GraphCoder method, we encountered an issue in the ccg.py file. The class of the language object at line 701 is Language and will not be equal to a string, and there are similar problems elsewhere, shouldn't it be language.name == ‘python’ or ‘java’？
<img width="363" alt="截屏2024-08-23 15 30 52" src="https://github.com/user-attachments/assets/6a1368a3-4875-4172-bb66-9db336bc1c80">

**Comment by oceaneLIU** [comment]
Thank you for your detailed feedback and for bringing this issue to our attention. As the code is still under development, we will review this matter and make the necessary updates accordingly.
